sonar.projectKey=joelalves_link-manager-ai_952b727b-254a-4eb7-bb31-b4693ed2764c
sonar.projectName=link-manager-ai

sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.venv/**,**/venv/**,**/__pycache__/**,**/coverage/**

sonar.sourceEncoding=UTF-8